# Generated by Django 3.2.7 on 2021-09-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('ref', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField()),
            ],
        ),
    ]
